// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using DAL.Entities;

namespace DAL.Context
{
    public partial class TelemedicineContext : DbContext
    {
        public TelemedicineContext()
        {
        }

        public TelemedicineContext(DbContextOptions<TelemedicineContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<Diagnosis> Diagnoses { get; set; }
        public virtual DbSet<DocAttacment> DocAttacments { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<DoctorSchedule> DoctorSchedules { get; set; }
        public virtual DbSet<Followup> Followups { get; set; }
        public virtual DbSet<MedicalDevice> MedicalDevices { get; set; }
        public virtual DbSet<MedicalRecord> MedicalRecords { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<Treatment> Treatments { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=Telemedicine;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Appointment>(entity =>
            {
                entity.HasOne(d => d.Admin)
                    .WithMany(p => p.Appointments)
                    .HasForeignKey(d => d.AdminId)
                    .HasConstraintName("admin control appointment");

                entity.HasOne(d => d.Doc)
                    .WithMany(p => p.AppointmentsNavigation)
                    .HasForeignKey(d => d.DocId)
                    .HasConstraintName("FK_appointment_doctors");

                entity.HasOne(d => d.Followup)
                    .WithMany(p => p.Appointments)
                    .HasForeignKey(d => d.FollowupId)
                    .HasConstraintName("appointment has many followup");

                entity.HasOne(d => d.Patient)
                    .WithMany(p => p.Appointments)
                    .HasForeignKey(d => d.PatientId)
                    .HasConstraintName("patient book an appointment");

                entity.HasOne(d => d.Scheduale)
                    .WithMany(p => p.Appointments)
                    .HasForeignKey(d => d.SchedualeId)
                    .HasConstraintName("FK_appointment_scheduale");
            });

            modelBuilder.Entity<Attachment>(entity =>
            {
                entity.HasOne(d => d.Followup)
                    .WithMany(p => p.Attachments)
                    .HasForeignKey(d => d.FollowupId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_followup_has_attachment");
            });

            modelBuilder.Entity<Diagnosis>(entity =>
            {
                entity.HasOne(d => d.Doc)
                    .WithMany(p => p.Diagnoses)
                    .HasForeignKey(d => d.DocId)
                    .HasConstraintName("FK_diagnosis_doctor");

                entity.HasOne(d => d.Patient)
                    .WithMany(p => p.Diagnoses)
                    .HasForeignKey(d => d.PatientId)
                    .HasConstraintName("FK__new_digno__patie__47A6A41B");
            });

            modelBuilder.Entity<DocAttacment>(entity =>
            {
                entity.HasOne(d => d.Doc)
                    .WithMany(p => p.DocAttacments)
                    .HasForeignKey(d => d.DocId)
                    .HasConstraintName("doctors has attachment");
            });

            modelBuilder.Entity<DoctorSchedule>(entity =>
            {
                entity.HasKey(e => e.ScheduleId)
                    .HasName("PK__TempDoct__C4BCB7371BB1F7A0");

                entity.HasOne(d => d.Doctor)
                    .WithMany(p => p.DoctorSchedules)
                    .HasForeignKey(d => d.DoctorId)
                    .HasConstraintName("FK__TempDocto__docto__2645B050");
            });

            modelBuilder.Entity<Followup>(entity =>
            {
                entity.HasOne(d => d.Doc)
                    .WithMany(p => p.Followups)
                    .HasForeignKey(d => d.DocId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_doctor_receive_message");

                entity.HasOne(d => d.Patient)
                    .WithMany(p => p.Followups)
                    .HasForeignKey(d => d.PatientId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_patient_send_message");
            });

            modelBuilder.Entity<MedicalRecord>(entity =>
            {
                entity.HasKey(e => e.RecordId)
                    .HasName("PK__medical___BFCFB4DD459675FF");
            });

            modelBuilder.Entity<Message>(entity =>
            {
                entity.HasOne(d => d.Followup)
                    .WithMany(p => p.Messages)
                    .HasForeignKey(d => d.FollowupId)
                    .HasConstraintName("FK_followup_has_messages");
            });

            modelBuilder.Entity<Report>(entity =>
            {
                entity.HasOne(d => d.DeviceNumberNavigation)
                    .WithMany(p => p.Reports)
                    .HasForeignKey(d => d.DeviceNumber)
                    .HasConstraintName("FK_Reports_medical_Device");

                entity.HasOne(d => d.Doc)
                    .WithMany(p => p.Reports)
                    .HasForeignKey(d => d.DocId)
                    .HasConstraintName("FK_Reports_Doctor");

                entity.HasOne(d => d.Patient)
                    .WithMany(p => p.Reports)
                    .HasForeignKey(d => d.PatientId)
                    .HasConstraintName("FK__NewReport__patie__3C34F16F");

                entity.HasOne(d => d.Record)
                    .WithMany(p => p.Reports)
                    .HasForeignKey(d => d.RecordId)
                    .HasConstraintName("FK__NewReport__recor__3D2915A8");
            });

            modelBuilder.Entity<Service>(entity =>
            {
                entity.HasOne(d => d.Admin)
                    .WithMany(p => p.Services)
                    .HasForeignKey(d => d.AdminId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("services added by an admin");
            });

            modelBuilder.Entity<Test>(entity =>
            {
                entity.HasOne(d => d.Patient)
                    .WithMany(p => p.Tests)
                    .HasForeignKey(d => d.PatientId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_test_patient");

                entity.HasOne(d => d.Service)
                    .WithMany(p => p.Tests)
                    .HasForeignKey(d => d.ServiceId)
                    .HasConstraintName("FK_test_services");
            });

            modelBuilder.Entity<Treatment>(entity =>
            {
                entity.HasOne(d => d.Doc)
                    .WithMany(p => p.Treatments)
                    .HasForeignKey(d => d.DocId)
                    .HasConstraintName("FK_treatment_doctor");

                entity.HasOne(d => d.Patient)
                    .WithMany(p => p.Treatments)
                    .HasForeignKey(d => d.PatientId)
                    .HasConstraintName("FK__new_treat__patie__44CA3770");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}