// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using DAL.Entities;

namespace DAL.Context
{
    public partial class TelemedicineContext : DbContext
    {
        public TelemedicineContext()
        {
        }

        public TelemedicineContext(DbContextOptions<TelemedicineContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<DeviceReading> DeviceReadings { get; set; }
        public virtual DbSet<Diagnosis> Diagnoses { get; set; }
        public virtual DbSet<DocAttacment> DocAttacments { get; set; }
        public virtual DbSet<DocConclusion> DocConclusions { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<Followup> Followups { get; set; }
        public virtual DbSet<MedicalDevice> MedicalDevices { get; set; }
        public virtual DbSet<MedicalRecord> MedicalRecords { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<TempDoctorSchedule> TempDoctorSchedules { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<TestAttachment> TestAttachments { get; set; }
        public virtual DbSet<TestsResult> TestsResults { get; set; }
        public virtual DbSet<Treatment> Treatments { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=Telemedicine;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Appointment>(entity =>
            {
                entity.HasOne(d => d.Admin)
                    .WithMany(p => p.Appointments)
                    .HasForeignKey(d => d.AdminId)
                    .HasConstraintName("admin control appointment");

                entity.HasOne(d => d.Doc)
                    .WithMany(p => p.AppointmentsNavigation)
                    .HasForeignKey(d => d.DocId)
                    .HasConstraintName("FK_appointment_doctors");

                entity.HasOne(d => d.Followup)
                    .WithMany(p => p.Appointments)
                    .HasForeignKey(d => d.FollowupId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("appointment has many followup");

                entity.HasOne(d => d.Patient)
                    .WithMany(p => p.Appointments)
                    .HasForeignKey(d => d.PatientId)
                    .HasConstraintName("patient book an appointment");

                entity.HasOne(d => d.Scheduale)
                    .WithMany(p => p.Appointments)
                    .HasForeignKey(d => d.SchedualeId)
                    .HasConstraintName("FK_appointment_scheduale");
            });

            modelBuilder.Entity<Attachment>(entity =>
            {
                entity.HasOne(d => d.Followup)
                    .WithMany(p => p.Attachments)
                    .HasForeignKey(d => d.FollowupId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_followup_has_attachment");
            });

            modelBuilder.Entity<DeviceReading>(entity =>
            {
                entity.HasKey(e => new { e.DeviceId, e.RecordId });

                entity.HasOne(d => d.Device)
                    .WithMany(p => p.DeviceReadings)
                    .HasForeignKey(d => d.DeviceId)
                    .HasConstraintName("medical device sen reading");

                entity.HasOne(d => d.Record)
                    .WithMany(p => p.DeviceReadings)
                    .HasForeignKey(d => d.RecordId)
                    .HasConstraintName("medical recore receive reading");
            });

            modelBuilder.Entity<Diagnosis>(entity =>
            {
                entity.Property(e => e.DiagnosisId).ValueGeneratedNever();

                entity.HasOne(d => d.Patient)
                    .WithMany(p => p.Diagnoses)
                    .HasForeignKey(d => d.PatientId)
                    .HasConstraintName("FK__diagnosis__patie__1EA48E88");

                entity.HasOne(d => d.Record)
                    .WithMany(p => p.Diagnoses)
                    .HasForeignKey(d => d.RecordId)
                    .HasConstraintName("FK__diagnosis__recor__1F98B2C1");
            });

            modelBuilder.Entity<DocAttacment>(entity =>
            {
                entity.HasOne(d => d.Doc)
                    .WithMany(p => p.DocAttacments)
                    .HasForeignKey(d => d.DocId)
                    .HasConstraintName("doctors has attachment");
            });

            modelBuilder.Entity<DocConclusion>(entity =>
            {
                entity.HasKey(e => new { e.DocId, e.RecordId });

                entity.HasOne(d => d.Doc)
                    .WithMany(p => p.DocConclusions)
                    .HasForeignKey(d => d.DocId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("doctor write prescription");

                entity.HasOne(d => d.Record)
                    .WithMany(p => p.DocConclusions)
                    .HasForeignKey(d => d.RecordId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("medical record receive prescription");
            });

            modelBuilder.Entity<Followup>(entity =>
            {
                entity.HasOne(d => d.Doc)
                    .WithMany(p => p.Followups)
                    .HasForeignKey(d => d.DocId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_doctor_receive_message");

                entity.HasOne(d => d.Patient)
                    .WithMany(p => p.Followups)
                    .HasForeignKey(d => d.PatientId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_patient_send_message");
            });

            modelBuilder.Entity<MedicalRecord>(entity =>
            {
                entity.HasKey(e => e.RecordId)
                    .HasName("PK__medical___BFCFB4DD459675FF");

                entity.HasOne(d => d.Patient)
                    .WithMany(p => p.MedicalRecords)
                    .HasForeignKey(d => d.PatientId)
                    .HasConstraintName("patient has medical record");
            });

            modelBuilder.Entity<Message>(entity =>
            {
                entity.HasOne(d => d.Followup)
                    .WithMany(p => p.Messages)
                    .HasForeignKey(d => d.FollowupId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_followup_has_messages");
            });

            modelBuilder.Entity<Report>(entity =>
            {
                entity.HasOne(d => d.Patient)
                    .WithMany(p => p.Reports)
                    .HasForeignKey(d => d.PatientId)
                    .HasConstraintName("FK__NewReport__patie__3C34F16F");

                entity.HasOne(d => d.Record)
                    .WithMany(p => p.Reports)
                    .HasForeignKey(d => d.RecordId)
                    .HasConstraintName("FK__NewReport__recor__3D2915A8");
            });

            modelBuilder.Entity<Service>(entity =>
            {
                entity.HasOne(d => d.Admin)
                    .WithMany(p => p.Services)
                    .HasForeignKey(d => d.AdminId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("services added by an admin");
            });

            modelBuilder.Entity<TempDoctorSchedule>(entity =>
            {
                entity.HasKey(e => e.ScheduleId)
                    .HasName("PK__TempDoct__C4BCB7371BB1F7A0");

                entity.HasOne(d => d.Doctor)
                    .WithMany(p => p.TempDoctorSchedules)
                    .HasForeignKey(d => d.DoctorId)
                    .HasConstraintName("FK__TempDocto__docto__2645B050");
            });

            modelBuilder.Entity<Test>(entity =>
            {
                entity.HasOne(d => d.Patient)
                    .WithMany(p => p.Tests)
                    .HasForeignKey(d => d.PatientId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_test_patient");

                entity.HasOne(d => d.Service)
                    .WithMany(p => p.Tests)
                    .HasForeignKey(d => d.ServiceId)
                    .HasConstraintName("FK_test_services");
            });

            modelBuilder.Entity<TestAttachment>(entity =>
            {
                entity.HasOne(d => d.Test)
                    .WithMany(p => p.TestAttachments)
                    .HasForeignKey(d => d.TestId)
                    .HasConstraintName("every test has attachment");
            });

            modelBuilder.Entity<TestsResult>(entity =>
            {
                entity.HasKey(e => new { e.TestId, e.RecordId });

                entity.HasOne(d => d.Record)
                    .WithMany(p => p.TestsResults)
                    .HasForeignKey(d => d.RecordId)
                    .HasConstraintName("medical record receives results");

                entity.HasOne(d => d.Test)
                    .WithMany(p => p.TestsResults)
                    .HasForeignKey(d => d.TestId)
                    .HasConstraintName("test sends results");
            });

            modelBuilder.Entity<Treatment>(entity =>
            {
                entity.Property(e => e.TreatmentId).ValueGeneratedNever();

                entity.HasOne(d => d.Patient)
                    .WithMany(p => p.Treatments)
                    .HasForeignKey(d => d.PatientId)
                    .HasConstraintName("FK__treatment__patie__22751F6C");

                entity.HasOne(d => d.Record)
                    .WithMany(p => p.Treatments)
                    .HasForeignKey(d => d.RecordId)
                    .HasConstraintName("FK__treatment__recor__236943A5");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}