// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities
{
    [Table("appointment")]
    [Index("AdminId", Name = "admin control appointment_idx")]
    [Index("FollowupId", Name = "appointment has many followup_idx")]
    [Index("PatientId", Name = "patient book an appointment_idx")]
    public partial class Appointment
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("appointment_date", TypeName = "datetime")]
        public DateTime AppointmentDate { get; set; }
        [Column("rate")]
        public double? Rate { get; set; }
        [Column("reservation_date", TypeName = "datetime")]
        public DateTime ReservationDate { get; set; }
        [Column("start")]
        public TimeSpan? Start { get; set; }
        [Required]
        [Column("place")]
        [StringLength(50)]
        public string Place { get; set; }
        [Column("patient_id")]
        public int PatientId { get; set; }
        [Column("status")]
        public int Status { get; set; }
        [Column("booking_receipt")]
        public string BookingReceipt { get; set; }
        [Column("followup_id")]
        public int? FollowupId { get; set; }
        [Column("admin_id")]
        public int? AdminId { get; set; }
        [Column("scheduale_Id")]
        public int? SchedualeId { get; set; }
        [Column("doc_id")]
        public int? DocId { get; set; }
        [Column("end_time")]
        public TimeSpan? EndTime { get; set; }
        [Column("patient_photo", TypeName = "image")]
        public byte[] PatientPhoto { get; set; }
        [Column("doctor_photo", TypeName = "image")]
        public byte[] DoctorPhoto { get; set; }
        [Column("patientName")]
        [StringLength(1)]
        [Unicode(false)]
        public string PatientName { get; set; }
        [Column("doctorName")]
        [StringLength(1)]
        [Unicode(false)]
        public string DoctorName { get; set; }
        public int? Price { get; set; }

        [ForeignKey("AdminId")]
        [InverseProperty("Appointments")]
        public virtual Admin Admin { get; set; }
        [ForeignKey("DocId")]
        [InverseProperty("AppointmentsNavigation")]
        public virtual Doctor Doc { get; set; }
        [ForeignKey("FollowupId")]
        [InverseProperty("Appointments")]
        public virtual Followup Followup { get; set; }
        [ForeignKey("PatientId")]
        [InverseProperty("Appointments")]
        public virtual Patient Patient { get; set; }
        [ForeignKey("SchedualeId")]
        [InverseProperty("Appointments")]
        public virtual DoctorSchedule Scheduale { get; set; }
    }
}