// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities
{
    [Table("attachment")]
    [Index("FollowupId", Name = "IX_followup_has_attachment")]
    public partial class Attachment
    {
        [Key]
        [Column("attah_id")]
        public int AttahId { get; set; }
        [Required]
        [Column("type")]
        [StringLength(10)]
        public string Type { get; set; }
        [Required]
        [Column("path")]
        public string Path { get; set; }
        [Column("date")]
        public DateTime Date { get; set; }
        [Column("followup_id")]
        public int FollowupId { get; set; }

        [ForeignKey("FollowupId")]
        [InverseProperty("Attachments")]
        public virtual Followup Followup { get; set; }
    }
}