// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities
{
    [Table("device_reading")]
    [Index("RecordId", Name = "medical recore receive reading_idx")]
    public partial class DeviceReading
    {
        [Key]
        [Column("device_id")]
        public int DeviceId { get; set; }
        [Key]
        [Column("record_id")]
        public int RecordId { get; set; }
        [Column("date")]
        public DateTime Date { get; set; }
        [Column("doctor_name")]
        [StringLength(50)]
        public string DoctorName { get; set; }
        [Required]
        [Column("result")]
        public string Result { get; set; }

        [ForeignKey("DeviceId")]
        [InverseProperty("DeviceReadings")]
        public virtual MedicalDevice Device { get; set; }
        [ForeignKey("RecordId")]
        [InverseProperty("DeviceReadings")]
        public virtual MedicalRecord Record { get; set; }
    }
}