// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities
{
    [Table("diagnosis")]
    public partial class Diagnosis
    {
        [Key]
        [Column("diagnosis_Id")]
        public int DiagnosisId { get; set; }
        [Column("Diagnosis", TypeName = "image")]
        public byte[] Diagnosis1 { get; set; }
        [Column("patient_Id")]
        public int? PatientId { get; set; }
        [Column("record_Id")]
        public int? RecordId { get; set; }
        [Column("doc_Id")]
        public int? DocId { get; set; }

        [ForeignKey("DocId")]
        [InverseProperty("Diagnoses")]
        public virtual Doctor Doc { get; set; }
        [ForeignKey("PatientId")]
        [InverseProperty("Diagnoses")]
        public virtual Patient Patient { get; set; }
    }
}