// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities
{
    [Table("doc_attacment")]
    [Index("DocId", Name = "doctors has attachment_idx")]
    public partial class DocAttacment
    {
        [Key]
        public int Id { get; set; }
        [Column("type")]
        [StringLength(50)]
        public string Type { get; set; }
        [Column("doc_id")]
        public int? DocId { get; set; }
        [Column("file", TypeName = "image")]
        public byte[] File { get; set; }

        [ForeignKey("DocId")]
        [InverseProperty("DocAttacments")]
        public virtual Doctor Doc { get; set; }
    }
}