// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities
{
    [Table("doc_conclusion")]
    [Index("RecordId", Name = "medical record receive prescription_idx")]
    public partial class DocConclusion
    {
        [Key]
        [Column("doc_id")]
        public int DocId { get; set; }
        [Key]
        [Column("record_id")]
        public int RecordId { get; set; }
        [Required]
        [Column("prescription")]
        public string Prescription { get; set; }

        [ForeignKey("DocId")]
        [InverseProperty("DocConclusions")]
        public virtual Doctor Doc { get; set; }
        [ForeignKey("RecordId")]
        [InverseProperty("DocConclusions")]
        public virtual MedicalRecord Record { get; set; }
    }
}