// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities
{
    [Table("medical_record")]
    public partial class MedicalRecord
    {
        public MedicalRecord()
        {
            Reports = new HashSet<Report>();
        }

        [Key]
        [Column("record_id")]
        public int RecordId { get; set; }
        [Column("patient_id")]
        public int PatientId { get; set; }

        [InverseProperty("Record")]
        public virtual ICollection<Report> Reports { get; set; }
    }
}