// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities
{
    [Table("medical_device")]
    [Index("Username", Name = "username_UNIQUE", IsUnique = true)]
    public partial class MedicalDevice
    {
        public MedicalDevice()
        {
            DeviceReadings = new HashSet<DeviceReading>();
        }

        [Key]
        [Column("device_number")]
        public int DeviceNumber { get; set; }
        [Column("date")]
        public DateTime Date { get; set; }
        [Required]
        [Column("username")]
        [StringLength(45)]
        public string Username { get; set; }
        [Required]
        [Column("password")]
        [StringLength(45)]
        public string Password { get; set; }

        [InverseProperty("Device")]
        public virtual ICollection<DeviceReading> DeviceReadings { get; set; }
    }
}