// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities
{
    [Table("medical_record")]
    public partial class MedicalRecord
    {
        public MedicalRecord()
        {
            DeviceReadings = new HashSet<DeviceReading>();
            Diagnoses = new HashSet<Diagnosis>();
            DocConclusions = new HashSet<DocConclusion>();
            Reports = new HashSet<Report>();
            TestsResults = new HashSet<TestsResult>();
            Treatments = new HashSet<Treatment>();
        }

        [Key]
        [Column("record_id")]
        public int RecordId { get; set; }
        [Column("patient_id")]
        public int PatientId { get; set; }

        [ForeignKey("PatientId")]
        [InverseProperty("MedicalRecords")]
        public virtual Patient Patient { get; set; }
        [InverseProperty("Record")]
        public virtual ICollection<DeviceReading> DeviceReadings { get; set; }
        [InverseProperty("Record")]
        public virtual ICollection<Diagnosis> Diagnoses { get; set; }
        [InverseProperty("Record")]
        public virtual ICollection<DocConclusion> DocConclusions { get; set; }
        [InverseProperty("Record")]
        public virtual ICollection<Report> Reports { get; set; }
        [InverseProperty("Record")]
        public virtual ICollection<TestsResult> TestsResults { get; set; }
        [InverseProperty("Record")]
        public virtual ICollection<Treatment> Treatments { get; set; }
    }
}