// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities
{
    [Table("message")]
    [Index("FollowupId", Name = "IX_followup_has_messages")]
    public partial class Message
    {
        [Key]
        [Column("message_id")]
        public int MessageId { get; set; }
        [Required]
        [Column("content", TypeName = "text")]
        public string Content { get; set; }
        [Column("date")]
        public DateTime Date { get; set; }
        [Column("followup_id")]
        public int FollowupId { get; set; }

        [ForeignKey("FollowupId")]
        [InverseProperty("Messages")]
        public virtual Followup Followup { get; set; }
    }
}