// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities
{
    [Table("reports")]
    public partial class Report
    {
        [Key]
        [Column("report_Id")]
        public int ReportId { get; set; }
        [Column("report", TypeName = "image")]
        public byte[] Report1 { get; set; }
        [Column("patient_Id")]
        public int? PatientId { get; set; }
        [Column("record_Id")]
        public int? RecordId { get; set; }

        [ForeignKey("PatientId")]
        [InverseProperty("Reports")]
        public virtual Patient Patient { get; set; }
        [ForeignKey("RecordId")]
        [InverseProperty("Reports")]
        public virtual MedicalRecord Record { get; set; }
    }
}