// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities
{
    [Table("services")]
    public partial class Service
    {
        public Service()
        {
            Tests = new HashSet<Test>();
        }

        [Key]
        [Column("service_id")]
        public int ServiceId { get; set; }
        [Column("service_price")]
        public int? ServicePrice { get; set; }
        [Required]
        [Column("service_name")]
        [StringLength(100)]
        [Unicode(false)]
        public string ServiceName { get; set; }
        [Column("service_place")]
        [StringLength(20)]
        [Unicode(false)]
        public string ServicePlace { get; set; }
        [Column("discount", TypeName = "decimal(18, 0)")]
        public decimal? Discount { get; set; }
        [Column("service_type")]
        public int? ServiceType { get; set; }
        [Column("admin_id")]
        public int AdminId { get; set; }

        [ForeignKey("AdminId")]
        [InverseProperty("Services")]
        public virtual Admin Admin { get; set; }
        [InverseProperty("Service")]
        public virtual ICollection<Test> Tests { get; set; }
    }
}