// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities
{
    [Table("TempDoctorSchedule")]
    public partial class TempDoctorSchedule
    {
        public TempDoctorSchedule()
        {
            Appointments = new HashSet<Appointment>();
        }

        [Key]
        [Column("schedule_Id")]
        public int ScheduleId { get; set; }
        [Column("doctor_Id")]
        public int? DoctorId { get; set; }
        [Column("day")]
        [StringLength(10)]
        [Unicode(false)]
        public string Day { get; set; }
        [Column("start_time")]
        public TimeSpan? StartTime { get; set; }
        [Column("end_time")]
        public TimeSpan? EndTime { get; set; }
        [Column("price", TypeName = "decimal(10, 2)")]
        public decimal? Price { get; set; }
        public int? Duration { get; set; }

        [ForeignKey("DoctorId")]
        [InverseProperty("TempDoctorSchedules")]
        public virtual Doctor Doctor { get; set; }
        [InverseProperty("Scheduale")]
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}