// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities
{
    [Table("test_attachment")]
    public partial class TestAttachment
    {
        [Key]
        [Column("attach_id")]
        public int AttachId { get; set; }
        [Required]
        [Column("path")]
        public string Path { get; set; }
        [Column("test_id")]
        public int TestId { get; set; }

        [ForeignKey("TestId")]
        [InverseProperty("TestAttachments")]
        public virtual Test Test { get; set; }
    }
}