// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities
{
    [Table("tests_result")]
    public partial class TestsResult
    {
        [Key]
        [Column("test_id")]
        public int TestId { get; set; }
        [Key]
        [Column("record_id")]
        public int RecordId { get; set; }
        [Required]
        [Column("result")]
        public string Result { get; set; }

        [ForeignKey("RecordId")]
        [InverseProperty("TestsResults")]
        public virtual MedicalRecord Record { get; set; }
        [ForeignKey("TestId")]
        [InverseProperty("TestsResults")]
        public virtual Test Test { get; set; }
    }
}