// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities
{
    [Table("treatments")]
    public partial class Treatment
    {
        [Key]
        [Column("treatment_Id")]
        public int TreatmentId { get; set; }
        [Column("treatment", TypeName = "image")]
        public byte[] Treatment1 { get; set; }
        [Column("patient_Id")]
        public int? PatientId { get; set; }
        [Column("record_Id")]
        public int? RecordId { get; set; }

        [ForeignKey("PatientId")]
        [InverseProperty("Treatments")]
        public virtual Patient Patient { get; set; }
        [ForeignKey("RecordId")]
        [InverseProperty("Treatments")]
        public virtual MedicalRecord Record { get; set; }
    }
}